# Netlify config for hohl.rocks
[build]
  publish = "public"

# Optional: if you add a build tool later (vite/parcel), set "command" accordingly.

[[redirects]]
  from = "/_api/*"
  to = "https://hohl-rocks-back-production.up.railway.app/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache headers for static assets
[[headers]]
  for = "/videos/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
