[build]
  publish = "public"

# Proxy to the fixed Railway host (both prefixes supported)
[[redirects]]
  from = "/_api/*"
  to   = "https://hohl-rocks-back-production.up.railway.app/:splat"
  status = 200
  force  = true

[[redirects]]
  from = "/api/*"
  to   = "https://hohl-rocks-back-production.up.railway.app/:splat"
  status = 200
  force  = true

# SPA fallback must come last
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
