[build]
  publish = "public"

# Proxy both /api/* and /_api/* to Railway (must be before fallback)
[[redirects]]
  from = "/api/*"
  to = "https://hohl-rocks-back-production.up.railway.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/_api/*"
  to = "https://hohl-rocks-back-production.up.railway.app/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
