# Netlify config for hohl.rocks (public publish)
[build]
  publish = "public"

# Proxy to Railway backend
[[redirects]]
  from = "/_api/*"
  to = "https://hohl-rocks-back-production.up.railway.app/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Long-lived cache
[[headers]]
  for = "/videos/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
