[build]
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "https://hohl-rocks-back-production.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/_api/*"
  to = "https://hohl-rocks-back-production.up.railway.app/_api/:splat"
  status = 200
  force = true
